using UnityEngine;

public class MovingPlatform : MonoBehaviour {

    public Vector3 finishPos = Vector3.zero;
    public float speed = 0.5f;

    // starts at location that object is set at.
    private Vector3 startPos;
    private float trackPercent = 0;
    private int direction = 1;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        startPos = transform.position;
    }

    // Update is called once per frame
    void Update()
    {
        trackPercent += direction * speed * Time.deltaTime;
        float x = (finishPos.x - startPos.x) * trackPercent + startPos.x;
        float y = (finishPos.y - startPos.y) * trackPercent + startPos.y;
        transform.position = new Vector3(x, y, startPos.z);

        if ((direction == 1 && trackPercent > 0.9) || (direction == -1 && trackPercent < 0.1f)) {
            direction *= -1;
        }
    }
}
